name: release

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: "http_helloworld"

jobs:
  multi-registries:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            guionardo/${{ env.IMAGE_NAME }}
          tags: |
            type=release
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1     
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: guionardo
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # registry: ghcr.io
          # username: ${{ github.repository_owner }}
          # password: ${{ secrets.CR_PAT }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build and push http microservice
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # tags: |
          #   guionardo/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
          # ghcr.io/guionardo/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
    
