name: release

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: "http_helloworld"

jobs:
  multi-registries:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1     
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: guionardo
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # registry: ghcr.io
          # username: ${{ github.repository_owner }}
          # password: ${{ secrets.CR_PAT }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build and push http microservice
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            guionardo/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            # ghcr.io/guionardo/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
    